# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Update NPM
        run: npm install -g npm
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run rollup
      - name: Upload Schedulely package artifact
        uses: actions/upload-artifact@v3
        with:
          name: schedulely-package
          path: ./packages/Schedulely
