name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Release Version
        id: getReleaseVersion
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Update NPM
        run: npm install -g npm

      - name: NPM Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        working-directory: ./packages/Schedulely
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

      ## Checkout so we can apply the new tag
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      ## Documentation: https://github.com/marvinpinto/action-automatic-releases
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
